[package]

name = "westwork"
version = "0.0.1"
authors = [ "Ross Schulman <ross@rbs.io>" ]

[dependencies]
rocket = "0.2.2"
rocket_codegen = "0.2.2"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]
