[package]

name = "westwork"
version = "0.0.1"
authors = [ "Ross Schulman <ross@rbs.io>" ]

[dependencies.config]
version = "0.4"
default-features = false
features = ["yaml"]

[dependencies]
rocket = "0.2.3"
rocket-codegen = "0.2.3"